# SITE CONFIGURATION
url: "blog.unetstack.net"
baseurl: ""
title: Unet Blog # site's title
description: "The Underwater Networks Project" # used by search engines


# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Unet # blog's title
  avatar: assets/img/unet.png
  favicon: assets/favicon.ico
  gravatar: # Email MD5 hash

  # Header and footer text
  header_text: > #two or three lines to describe your site
     <h1>Unet Blog</h1><p>The Underwater Networks Project</p>
  header_text_feature_image: assets/img/water.jpg
  search_header_text: > #two or three lines to describe your site
     <h1>Search</h1><p>What are you looking for?</p>
  about_header_text: > #two or three lines to describe your site
     <h1>About</h1>
  footer_text: >
    © Unet Project

  # Icons
  rss: true  # Make sure you created a feed.xml with feed.xml layout
  github: "org-arl/unet-contrib"
  stack_exchange:  "https://stackoverflow.com/questions/tagged/unetstack"
  twitter:  "@unetstack"
  youtube:  "UCnwSva23AuUCFPqgI0kPvdw"

  # Scripts / Features
  google_analytics: "UA-52885583-1" # Tracking ID, e.g. "UA-000000-01"
  katex: true # Enable if using math markup

  navbar_links:
    UnetStack:
      url: "https://www.unetstack.net/"
      enabled: true
    Unet-Contrib:
      url: "https://github.com/org-arl/unet-contrib"
      enabled: true

  special_page:
    search:
      icon: "search" # Assuming page link and icon are the same
      enabled: true
    tags:
      icon: "tags"
      enabled: true

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_share_on: "Share on"
  str_add_to: "Add to"
  str_email: "Email"
  str_tweet: "Tweet"
  str_pin_it: "Pin it"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true

# PERMALINK
permalink: /:title

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag]
#theme: type-on-strap # Uncomment if using the theme as a jekyll theme gem
exclude: ["LICENSE", "README.md", "screenshot.png", "gulpfile.js", ".idea/*"]
